### ISSUE TITLE
No SSH keys generated for `alces` user

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#31] opened 2015-12-29 12:19 UTC
The default Alces AMI has been reconfigured to create and set (using cloud-init) the `alces` user as the admin user instead of the default `centos`. The `alces` user does not work as expected: 

As `alces` administrator user:

```
[alces@login1(awscluster) ~]$ pdsh -g all 'uptime'
node1: Host key verification failed.
pdsh@login1: node1: ssh exited with exit code 255
node4: Host key verification failed.
pdsh@login1: node4: ssh exited with exit code 255
login1: Host key verification failed.
pdsh@login1: login1: ssh exited with exit code 255
node5: Host key verification failed.
pdsh@login1: node5: ssh exited with exit code 255
node2: Host key verification failed.
pdsh@login1: node2: ssh exited with exit code 255
node3: Host key verification failed.
pdsh@login1: node3: ssh exited with exit code 255
[alces@login1(awscluster) ~]$ ssh node1
The authenticity of host 'node1 (10.75.0.242)' can't be established.
RSA key fingerprint is 14:3b:f0:9c:7d:81:62:0a:62:ad:17:cb:25:c7:45:11.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'node1,10.75.0.242' (RSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

Whilst using `centos` as the default administrator user: 

```
[centos@login1(awscluster) ~]$ pdsh -g all 'uptime'
login1:  12:17:49 up 5 min,  1 user,  load average: 0.02, 0.10, 0.05
node1:  12:17:49 up 4 min,  0 users,  load average: 0.03, 0.13, 0.07
[centos@login1(awscluster) ~]$ ssh node1
Last login: Mon Dec 14 10:34:11 2015 from 213.83.69.6
                 +++++++++++++++++++++++++++++++++++++++++++++
                             Welcome to awscluster
                     An Alces Clusterware environment (r3)
                              Based on CentOS 6.7
                 +++++++++++++++++++++++++++++++++++++++++++++
TIPS:

'module avail'            - show available application environments
'module add <modulename>' - add a module to your current environment

'alces session'           - start and manage interactive sessions
'alces gridware'          - manage software for your environment
'alces howto'             - guides on how to use your research environment
'alces template'          - tailored job script templates

'qstat'                   - show summary of running jobs
'qsub'                    - submit a job script
'qdesktop'                - submit an interactive session request
```

**Comment by mjtko** [comment] 2015-12-29 12:24
Duplicate of #27.

**Comment by mjtko** [comment] 2016-01-04 12:24
As [discussed](https://alces.slack.com/archives/clusterware/p1451391899000623) we'll remove the `alces` user from the skip list in the `setup-sshkey.rc` configuration file.

**Closed as completed** 2016-01-04 13:41 UTC
Labels: bug
