### ISSUE TITLE
Error when installing Depot

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#149] opened 2016-05-17 09:42 UTC
```
[alces@login1(hpc1) ~]$ alces gridware depot install benchmark
Installing depot: benchmark

 > Initializing depot: benchmark
      Initialize ... OK

Importing mpi-openmpi-1.8.5-el7.tar.gz

 > Fetching archive
        Download ... OK

 > Preparing import
         Extract ... OK
          Verify ... OK

 > Processing mpi/openmpi/1.8.5/gcc-4.8.5
       Preparing ... OK
       Importing ... OK
     Permissions ... OK

 > Finalizing import
          Update ... OK
    Dependencies ... OK

Importing libs-atlas-3.10.2-el7.tar.gz

 > Fetching archive
        Download ... OK

 > Preparing import
         Extract ... OK
          Verify ... OK

 > Processing libs/atlas/3.10.2/gcc-4.8.5
       Preparing ... OK
       Importing ... OK
     Permissions ... OK

 > Finalizing import
          Update ... OK
    Dependencies ... OK

Importing apps-memtester-4.3.0-el7.tar.gz

 > Fetching archive
        Download ... OK

 > Preparing import
         Extract ... OK
          Verify ... OK

 > Processing apps/memtester/4.3.0/gcc-4.8.5
       Preparing ... OK
       Importing ... OK
     Permissions ... OK

 > Finalizing import
          Update ... OK
    Dependencies ... OK

Importing apps-iozone-3.420-el7.tar.gz

 > Fetching archive
        Download ... OK

 > Preparing import
         Extract ... OK
          Verify ... OK

 > Processing apps/iozone/3.420/gcc-4.8.5
       Preparing ... OK
       Importing ... OK
     Permissions ... OK

 > Finalizing import
          Update ... OK
    Dependencies ... OK

Importing apps-imb-4.0-el7.tar.gz

 > Fetching archive
        Download ... OK

 > Preparing import
         Extract ... OK
          Verify ... OK

 > Processing apps/imb/4.0/gcc-4.8.5+openmpi-1.8.5
       Preparing ... OK
       Importing ... error: database is locked (code: 5, sql state: , query: INSERT INTO "alces_packager_packages" ("type", "name", "version", "tag", "compiler_tag", "path", "default") VALUES ('apps', 'imb', '4.0', 'gcc-4.8.5+openmpi-1.8.5', 'gcc-4.8.5', 'apps/imb/4.0/gcc-4.8.5+openmpi-1.8.5', 't'), uri: sqlite3:/opt/gridware/depots/8153b7b7/el7/etc/package.db?scheme=sqlite&user=&password=&host=&port=&query=&fragment=&adapter=sqlite3&path=/opt/gridware/depots/8153b7b7/el7/etc/package.db). Use --trace to view backtrace
```

Image built from `hotfix/1.5.1` branch, running on OpenStack

**Comment by mjtko** [comment] 2016-08-01 14:53
@vlj91: is this easily reproducible?

I can imagine that this could happen if there are multiple imports/installs going on simultaneously but it shouldn’t happen under "normal" conditions.

**Comment by bobwhitelock** [comment] 2016-10-17 17:28
This looks like the same issue as https://github.com/alces-software/clusterware/issues/213.

**Comment by bobwhitelock** [comment] 2016-11-28 12:30
Closing as duplicate.

**Closed as completed by bobwhitelock** 2016-11-28 12:30 UTC
Labels: duplicate
